### ISSUE TITLE
No support for Atomic Extension (RVA)

### ISSUE THREAD

**Issue by neelayjunnarkar** [noloerino/duna#7]
# Description

None of the extensions in the RVA extension are supported.

# Reproduce

Use any of the atomic structions.

**Comment by noloerino** [comment]
There's (very long-term) plans in the works to extend the emulator to various ISA extensions, but I feel the codebase isn't structurally ready yet to support more instructions. It's not because it isn't possible, it's just that the current interface is very unergonomic, and I don't want to waste time refactoring later if I come up with a better design for managing simulation state and declaring new instructions.

Moreover, atomics in particular aren't really a priority since the design is currently single-threaded: I'd like to eventually allow the simulator to simulate different CPU scheduling policies, but this is something that's really far out.

I'll mark this issue as closed for now since this isn't going to be landed any time soon - I'll revisit this in the future if possible.

**Comment by neelayjunnarkar** [comment]
I hope this is supported eventually. It would be useful not just for actually multithreaded code, but for plugging in existing Risc-V assembly written with multi-threaded programs in mind, but actually being used in a single-thread. This way I can just plug in my code without changing all the atomics to the non-atomic versions.

**Comment by noloerino** [comment]
While that's a fair consideration, I'd imagine the vast majority of use
cases for multithreaded code requires the main thread to spawn multiple
children threads; it doesn't really make sense to implement `fork`,
`pthread_create` and similar syscalls if I don't create another logical
thread/process since the main thread would rarely do any meaningful work if
the child isn't spawned. Most programs that make use of concurrency
primitives/atomics would also require multiple threads to be running in
order for the output to be meaningful, and I don't think it makes sense to
take the time to implement atomic instructions (even if they're no-ops) if
the use cases for them would be stunted by the lack of other more
substantial features anyway.
